Include .crates.toml in Rust example
Using the existing example, cargo install will error out after restoring a cache:
```
cargo install cargo-tarpaulin
    Updating crates.io index
error: binary `cargo-tarpaulin` already exists in destination
Add --force to overwrite
Error: Process completed with exit code 101.
```

`--force` is undesirable because it will recompile the binary.  Cargo is scared of the existing binary because it doesn't have enough information about it.  Including `~/.cargo/.crates.toml` coaxes it into being okay with the situation.